# Generated by Django 2.2.17 on 2020-11-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_detalleventa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id']},
        ),
    ]
