# Generated by Django 2.2.17 on 2020-11-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201115_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['id']},
        ),
    ]
